### ISSUE TITLE
Improve service generation

### ISSUE THREAD

**Issue by AnthonyMichaelTDM** [Wulf/create-rust-app#102]
Currently, using the cli to add a new service to a project will create an incomplete service with outdated naming conventions

**Comment by AnthonyMichaelTDM** [comment]
just had a thought,

should service generation be it's own program (like how dsync and tsync are)? or maybe not because it would theoretically only work if the users models follow the naming conventions of dsync's generated models...

**Comment by Wulf** [comment]
I'm going to push a fix for the current service template which will also remove model generation because dsync takes care of that now

**Comment by Wulf** [comment]
I improved the generated service, but feel free create another PR :)

Closing this for now
