### ISSUE TITLE
support Axum and warp for backend

### ISSUE THREAD

**Issue by kindlychung** [Wulf/create-rust-app#11]

**Comment by Wulf** [comment]
hey @kindlychung, hope things are well.

Axum, warp, and rocket are in the `docs/TODO.md` list :)

I don't know if I can get to them anytime soon, let alone maintaining the frameworks afterwards. Would appreciate any help with this!

**Comment by Wulf** [comment]
I've added outlines for axum and warp to be added. I'm closing this issue but please feel free to continue the discussion in the new issues or here.
