### ISSUE TITLE
Feature Request - Option to have no Database

### ISSUE THREAD

**Issue by matty-r** [Wulf/create-rust-app#12]
Thanks for this project, it's super handy. 
One option i'd like to see, especially when just learning, is the option to have no Database in the backend and just have the bare minimum to get the server going with the base create-react-app page loaded.

**Comment by Wulf** [comment]
hey @matty-r, hope things are well.

Could I ask if something like instructions to setup a database real fast (with docker, for example -- or an in-memory SQLite db) be of help in your case?

**Comment by matty-r** [comment]
Hi @Wulf thanks for responding. There are plenty of instructions around for setting something like that up. Its just at an early point its not necessary when you're just prototyping/learning the basics.

Just a thought anyway. When you're just trying the learn the very basics of putting the app together, sometimes the additional overhead of learning DB calls / hooks / etc.. Is a bit much.

**Comment by Wulf** [comment]
Ah, so it's not the friction of setting up a database that's bothering you, but rather that there is too many things going on in the created project -- does that sound right?

**Comment by Wulf** [comment]
hey @matty-r thanks again for the feedback, from what I gathered and understood, I think #26 should resolve this. Closing for now, feel free to reopen.
