### ISSUE TITLE
out-of-date readme and help messages

### ISSUE THREAD

**Issue by AnthonyMichaelTDM** [Wulf/create-rust-app#141]
readme and help messages still refer to the Dev plugin (which is now enabled by default)

this may not be intended

**Comment by Wulf** [comment]
yeah we should make a note in the readme about this

Also something about falling back to `cargo backend` and `cargo frontend` if you prefer having your compiler messages in the terminal (and basically not using plugin_dev)

**Comment by AnthonyMichaelTDM** [comment]
I'm gonna be removing references to it from the CLI in a branch I'm working on,

also fixing clippy warnings and adding tests to ensure a situation like #140 is caught next time

**Comment by AnthonyMichaelTDM** [comment]
I fixed most of this in #142, so i'll close it for now
