### ISSUE TITLE
Template code should Authenticate with Bearer Token

### ISSUE THREAD

**Issue by roblperry** [Wulf/create-rust-app#143]
After signing into the client application the Account page is blank.  Looking in the console, I see several errors starting with:

`AccountPage.tsx:71          GET http://localhost:3000/api/auth/sessions?page=0&page_size=10 401 (Unauthorized)`

If I modify line 73-75 from:

```
headers: {
  Authorization: `${auth.accessToken}`,
}
```

to

```
headers: {
  Authorization: `Bearer ${auth.accessToken}`,
}
```

The page `GET http://localhost:3000/api/auth/sessions` succeeds. 

This appears to be a result of addressing Issue #87

**Comment by AnthonyMichaelTDM** [comment]
merged the fix, closing the issue

feel free to re-open if neededd
