### ISSUE TITLE
No such file or directory error from project.rs

### ISSUE THREAD

**Issue by Jarvismkennedy** [Wulf/create-rust-app#160]
The create-rust-app cli is always giving me this error: 

`thread 'main' panicked at 'failed to execute process: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/jarviskennedy/.cargo/registry/src/github.com-1ecc6299db9ec823/create-rust-app_cli-9.0.0/src/content/project.rs:274:10`

**Comment by Wulf** [comment]
hey @Jarvismkennedy, hope things are well :)

Sorry you ran into this. Could I ask which commands you ran exactly? For example, the following is working for me:

```sh
cargo install create-rust-app_cli

create-rust-app my-project 
# all plugins enabled, using all permutations of actix-web/poem/sqlite/postgres
```

**Comment by Jarvismkennedy** [comment]
Hey, thanks for the response!

I ran `cargo install create-rust-app_cli`, and then `create-rust-app my_project` and I get this error with any permutation of options I choose. The error is always the same, at project.rs:274:10.

**Comment by Wulf** [comment]
:thinking: that's really strange. Could you run:

```
create-rust-app --version
```

**Comment by Jarvismkennedy** [comment]
Yes, I am on version 9.0.0

**Comment by Wulf** [comment]
What does the following return?

```
tree /Users/jarviskennedy/.cargo/registry/src/github.com-1ecc6299db9ec823/create-rust-app_cli-9.0.0/
```

(you can `brew install tree` if necessary)

**Comment by Wulf** [comment]
I ended up finding and fixing a different bug -- please do share the output of
```
tree /Users/jarviskennedy/.cargo/registry/src/github.com-1ecc6299db9ec823/create-rust-app_cli-9.0.0/
```
when you get a chance. Again, you can `brew install tree` if necessary!

**Comment by Jarvismkennedy** [comment]
Here is the result: 

`├── Cargo.lock
├── Cargo.toml
├── Cargo.toml.orig
├── src
│   ├── content
│   │   ├── cargo_toml.rs
│   │   ├── migration.rs
│   │   ├── mod.rs
│   │   ├── model.rs
│   │   ├── project.rs
│   │   └── service.rs
│   ├── main.rs
│   ├── plugins
│   │   ├── auth.rs
│   │   ├── container.rs
│   │   ├── dev.rs
│   │   ├── graphql.rs
│   │   ├── mod.rs
│   │   ├── storage.rs
│   │   └── utoipa.rs
│   └── utils
│       ├── fs.rs
│       ├── git.rs
│       ├── logger.rs
│       └── mod.rs
├── template
│   ├── README.md
│   ├── backend
│   │   ├── mail
│   │   │   ├── example.rs
│   │   │   └── mod.rs
│   │   ├── main.rs+actix_web
│   │   ├── main.rs+poem
│   │   ├── models
│   │   │   └── mod.rs
│   │   ├── schema.rs
│   │   ├── services
│   │   │   ├── mod.rs
│   │   │   ├── todo.rs+actix_web
│   │   │   └── todo.rs+poem
│   │   └── views
│   │       └── index.html
│   ├── build.rs
│   ├── diesel.toml
│   ├── frontend
│   │   ├── bundles
│   │   │   └── index.tsx
│   │   ├── package-lock.json
│   │   ├── package.json
│   │   ├── playwright.config.ts
│   │   ├── public
│   │   │   ├── images
│   │   │   │   ├── favicon.ico
│   │   │   │   ├── logo192.png
│   │   │   │   └── logo512.png
│   │   │   ├── pwa.json
│   │   │   └── robots.txt
│   │   ├── src
│   │   │   ├── App.css
│   │   │   ├── App.tsx
│   │   │   ├── containers
│   │   │   │   ├── Home.tsx
│   │   │   │   └── Todo.tsx
│   │   │   ├── dev.tsx
│   │   │   ├── hooks
│   │   │   │   └── useQueryParam.ts
│   │   │   ├── images
│   │   │   │   ├── logo.svg
│   │   │   │   ├── logo2.svg
│   │   │   │   └── plus.svg
│   │   │   ├── reportWebVitals.js
│   │   │   └── types
│   │   │       ├── global.d.ts
│   │   │       ├── rust.d.ts
│   │   │       └── untyped-modules.d.ts
│   │   ├── tests
│   │   │   └── example.spec.ts
│   │   ├── tsconfig.json
│   │   └── vite.config.ts
│   └── migrations
│       ├── 00000000000000_diesel_initial_setup
│       │   ├── down.sql+database_postgres
│       │   └── up.sql+database_postgres
│       ├── 00000000000001_utc
│       │   ├── down.sql+database_postgres
│       │   └── up.sql+database_postgres
│       └── 00000000000002_todos
│           ├── down.sql+database_postgres
│           ├── down.sql+database_sqlite
│           ├── up.sql+database_postgres
│           └── up.sql+database_sqlite
├── template-plugin-auth
│   └── frontend
│       ├── src
│       │   ├── containers
│       │   │   ├── AccountPage.tsx
│       │   │   ├── ActivationPage.tsx
│       │   │   ├── LoginPage.tsx
│       │   │   ├── RecoveryPage.tsx
│       │   │   ├── RegistrationPage.tsx
│       │   │   └── ResetPage.tsx
│       │   ├── hooks
│       │   │   └── useAuth.tsx
│       │   └── types
│       │       └── plugin-auth.d.ts
│       └── tests
│           └── authentication.spec.ts
├── template-plugin-container
│   └── Dockerfile
├── template-plugin-dev
│   ├── README.md
│   └── frontend
│       └── src
│           ├── setupDevelopment.tsx
│           └── types
│               └── plugin-dev.d.ts
├── template-plugin-graphql
│   ├── backend
│   │   └── graphql
│   │       ├── mod.rs+actix_web
│   │       ├── mod.rs+poem
│   │       ├── mutation.rs
│   │       ├── query.rs
│   │       └── subscription.rs
│   └── frontend
│       └── src
│           ├── containers
│           │   └── GraphQLPage.tsx
│           └── hooks
│               └── useAuthenticatedApolloClient.ts
└── template-plugin-storage
    ├── backend
    │   └── services
    │       ├── file.rs+actix_web
    │       └── file.rs+poem
    └── frontend
        └── src
            ├── containers
            │   └── Files.tsx
            └── types
                └── plugin-storage.d.ts`

**Comment by AnthonyMichaelTDM** [comment]
> Update: It seems we've changed the order of git commands -- was [this](https://github.com/Wulf/create-rust-app/commit/bf46fa090249bd40e5e9d172ad027eb54dc9879b#diff-39d2748a92ddeabb1484bfec89431c0a0c3e79feb7a110241fed570fa7e8da7cR263) necessary for the CI setup @AnthonyMichaelTDM ? It's completely broken the normal flow (since we need to create an initialize the git directory before asking the user for their name/email). Hmm, continued to check and it shouldn't be necessary since we modify the global git [config](https://github.com/Wulf/create-rust-app/commit/bf46fa090249bd40e5e9d172ad027eb54dc9879b#diff-2d3e26ba7cc72eb42c62f25e5f444434c9e8245723ad4fdc1cb013d84961f9aeR42). Going to revert this move~

I changed it to set the git username/email before creating any files, the CI must not've caught issues that caused because of the issue brought up in #140 , which judging from the fact this error pops up now indicates that #140 may be fixed.

I'll start working on a bugfix to bring the order back to what it originally was right now

**Comment by AnthonyMichaelTDM** [comment]
the specific issue is that part of checking for a git username/email is reading a git configuration in `project_dir`, which doesn't exist as it would be created in this code block 
```rust
match std::fs::create_dir_all(&project_dir) {
    Ok(_) => {}
    Err(err) => logger::exit("std::fs::create_dir_all():", err),
}
```

the bug fix will move that block back before checking for username/email
