### ISSUE TITLE
BUG: cannot find REQUEST_REFRESH_COUNT in this scope

### ISSUE THREAD

**Issue by AnthonyMichaelTDM** [Wulf/create-rust-app#168]
unsure what's causing this, may be linked to the new rust update as I only noticed it after updating to 1.68

![image](https://user-images.githubusercontent.com/68485672/224451966-ed9b92ac-4e72-47b7-8d1d-c23a6b852389.png)

here's the relevant part of the code too:

https://github.com/Wulf/create-rust-app/blob/ca1a6a0092c263dbcbfd49a1c42a3fd31e3741d3/create-rust-app/src/util/actix_web_utils.rs#L35-L91

**Comment by AnthonyMichaelTDM** [comment]
This issue only pops up in compilation profiles that don't have debug_assertions turned on, so that's probably the cause

not sure if the proper fix is to move usages of the variable into a conditionally compiled block, or to remove the declaration of it from the block

**Comment by Wulf** [comment]
Yeah, I saw this when looking into the git issue -- the code block in line 56 should be inside the debug assertion block on line 52.

**Comment by Wulf** [comment]
Sorry you had to run into this Anothony, I should've just pushed my local fixes up last weekend but what prevented me in doing so was my inability to test everything because it wasn't compiling (due to the watchexec situation).

**Comment by Wulf** [comment]
Apparently I had done all this work in poem which is why the actix-web version [was broken](https://github.com/Wulf/create-rust-app/pull/181/files#diff-6826f212ba6448a9215e055074c2db228f98f20addc91b15b1e441ce626a74cfR56-R59) :sweat_smile: 

Anyway, it should be fixed in 9.1.0!
