### ISSUE TITLE
how to switch sqlite

### ISSUE THREAD

**Issue by zhaopengme** [Wulf/create-rust-app#17]
I tried to use sqlite, but it didn't work. How do I switch to sqlite?
thanks

**Comment by Wulf** [comment]
Ah darn I just realized the helper crate defines `Connection` as a postgres connection type...

I'll have to do some refactoring to get it to work with other database, super sorry about this!~

**Comment by Wulf** [comment]
hey @zhaopengme, thanks again for reporting this issue! I finally got around to resolving some of the finer details around integrating sqlite support. You can find SQLite support in `create-rust-app_cli@8.0.1` :)
