### ISSUE TITLE
Compilation error after creating the app 

### ISSUE THREAD

**Issue by boggye** [Wulf/create-rust-app#314]
Hi,

I created the directory and the code as per the instructions in the documentation and when I ran `cargo fullstack` I got the error below:
```
error[E0063]: missing fields `model_path` and `schema_path` in initializer of `GenerationConfig<'_>`
  --> .cargo/bin/dsync.rs:19:52
   |
19 |     dsync::generate_files(schema_file, models_dir, GenerationConfig {
   |                                                    ^^^^^^^^^^^^^^^^ missing `model_path` and `schema_path`

```

After some trial and error, this is the fix I applied:
```
pub fn main() {
    let dir = env!("CARGO_MANIFEST_DIR");

    println!("Running dsync (generating model code from `backend/schema.rs`)");

    let schema_file = PathBuf::from_iter([dir, "backend/schema.rs"]);
    let models_dir = PathBuf::from_iter([dir, "backend/models"]);

    let model_path = "models::".to_string();    // <-------------------
    let schema_path = "crate::schema::".to_string();    // <-------------------

    ensure_schema_is_generated(&schema_file);

    dsync::generate_files(schema_file, models_dir, GenerationConfig {
        connection_type: "create_rust_app::Connection".to_string(),
        default_table_options: TableOptions::default()
            .tsync()
            .autogenerated_columns(vec!["id", "created_at", "updated_at"]),
        table_options: HashMap::from([
            // plugin_storage
            ("attachment_blobs", TableOptions::default().ignore()),
            ("attachments", TableOptions::default().ignore()),

            // plugin_auth
            ("role_permissions", TableOptions::default().ignore()),
            ("user_permissions", TableOptions::default().ignore()),
            ("user_roles", TableOptions::default().ignore()),
            ("user_sessions", TableOptions::default().ignore()),
            ("users", TableOptions::default().ignore()),

            // plugin_tasks
            ("fang_tasks", TableOptions::default().ignore()),
         ],
        ),
        model_path,   // <-------------------
        schema_path,   // <-------------------
    });
}
```

So, could you please fix this, or if I did something wrong, which is entirely possible because I am new to the rust ecosystem, could you please update the docs to outline clearly the steps that need to be done in order to successfully run the app?

Thank you,
🙏

**Comment by Kalmarv** [comment]
Same issue here

**Comment by AnthonyMichaelTDM** [comment]
This is probably due to a new release of dsync, for now try using an older version (of dsync) while I work on a fix (which might take me a while because I don't have a lot of free bandwidth right now

**Comment by AnthonyMichaelTDM** [comment]
also, shouldn't model_path be "crate::models::" or did that not work?

see: https://github.com/Wulf/dsync/commit/ec866873bc1d074000082a03a0011bb548e9f39c (the breaking change)

**Comment by AnthonyMichaelTDM** [comment]
> This is probably due to a new release of dsync, for now try using an older version (of dsync) while I work on a fix (which might take me a while because I don't have a lot of free bandwidth right now

actually nvm, issue was much smaller than I first thought, thanks for providing your fix @boggye

**Comment by AnthonyMichaelTDM** [comment]
do note, even after fix is pushed it may take a while to be shipped bc I don't control releases

**Comment by AnthonyMichaelTDM** [comment]
(will close when fixes are released)

**Comment by Wulf** [comment]
Thanks for jumping on this
