### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by alenandry** [Wulf/create-rust-app#46]
```
 Compiling rust_app v0.1.0 (/rust_app)
error: linking with `cc` failed: exit status: 1
= note: /usr/bin/ld: cannot find -lpq: No such file or directory
```

**Comment by Wulf** [comment]
Hey @alenandry, could you try installing diesel_cli first?

Here are the instructions:
http://diesel.rs/guides/getting-started#installing-diesel-cli

**Comment by Wulf** [comment]
hey @alenandry I'm going to close this  but feel free to re-open it if you still need help.

A hint for any visitors in the future:
`note: /usr/bin/ld: cannot find -lpq: No such file or directory` is indicating that libpq is missing!

One of the requirements for create-rust-app is the diesel_cli which won't work unless you libX (depending on which database you're using) -- see the link I've shared above.
