### ISSUE TITLE
Schema.rs is empty

### ISSUE THREAD

**Issue by gstrike-glassbox** [Wulf/create-rust-app#47]
The todo.rs within models and services complains that `failed to resolve: could not find todos in schema` which makes sense as the file is empty. 
Is this expected behaviour? Are we meant to build the schema ourselves? :) 
This prevents cargo from building.

**Comment by gstrike-glassbox** [comment]
Ignore this, this was me being a moron lol.

**Comment by kirtcathey** [comment]
then what was it?
