### ISSUE TITLE
I want to contribute to this projects

### ISSUE THREAD

**Issue by Santiago-Torres14** [Wulf/create-rust-app#48]
Hey, I did not how to contact you, so I decided to open a Issue. I'd love to contribute to this project because I was looking for something like, I even thought about building one myself, but I found this projects which is quite advance. Maybe we could talk send me a message...

**Comment by Wulf** [comment]
hey @Santiago-Torres14, thanks for reaching out -- I'd love the help. I've been slowly working away to improve the Admin UI (#30) and email builder (#37). If you'd like to jump on some of the existing issues, I can help you get started or if there's something particular you'd like to work on, feel free to create more issues.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/4259838/179454676-5ec41539-5a09-4091-a86f-3834f3c5af4f.png">

<img width="911" alt="image" src="https://user-images.githubusercontent.com/4259838/179454867-6f1d8148-7b95-413e-9d57-c6413e0f3299.png">

<img width="903" alt="image" src="https://user-images.githubusercontent.com/4259838/179454876-c306ed4a-6db0-4682-9b49-ed61a5bf1d25.png">

<img width="702" alt="image" src="https://user-images.githubusercontent.com/4259838/179454626-8e88e668-bc75-4047-9978-a488bb9a518b.png">
