### ISSUE TITLE
`CASCADE ALL` in postgresql `down.sql` files.

### ISSUE THREAD

**Issue by XBagon** [Wulf/create-rust-app#57]
`DROP TABLE table_name CASCADE ALL;` doesn't seem to be valid syntax. The `ALL` at the end is too much.
Found this out while trying to do `diesel migration revert`.

Example: [migrations/00000000000002_todos/down.sql+database_postgres](https://github.com/Wulf/create-rust-app/blob/970df9c7fc2b748fa0ff6fb4d13dce1fec8149b6/create-rust-app_cli/template/migrations/00000000000002_todos/down.sql%2Bdatabase_postgres)

**Comment by Wulf** [comment]
Ah darn, I wrote those by hand and never tested them. You're right, that ALL doesn't belong there. If you've got a moment for a quick PR, please do create one -- otherwise, leave this to me and I'll fix it soon!~

**Comment by Wulf** [comment]
Hopefully fixed in `8.1.0`; closing for now feel free to reopen :)
