### ISSUE TITLE
redis plugin and more

### ISSUE THREAD

**Issue by himothy2110** [Wulf/create-rust-app#59]
I love to see Redis, Hadoop, Kafka etc added as plugins
also I'd love to talk about the project and how I could help out on discord

**Comment by Wulf** [comment]
hey @himothy2110, thanks for opening this issue -- sorry I'm replying so late, it has been a busy few weeks.

Those plugins sound like great additions. I've already got an issue for Redis (#29). Let me know if you're still available to help out and I can hop on discord with you.

**Comment by himothy2110** [comment]
yeah sorry for the late reply too, my discord is danikhan632#2543
I'd also love to make some documentation for this
