### ISSUE TITLE
backend/schema.rs is empty or not present

### ISSUE THREAD

**Issue by wstrinz** [Wulf/create-rust-app#67]
After running `create-rust-app my-todo-app`, and choosing postgres, actix-web, and all plugins I get

```
   Compiling create-rust-app v8.1.0
    Finished dev [unoptimized + debuginfo] target(s) in 1m 06s
     Running `.cargo/.build/debug/dsync`
thread 'main' panicked at '`backend/schema.rs` is empty or not present', .cargo/bin/dsync.rs:42:9
```

This is on Ubuntu 22.04 running in WSL.

**Comment by Wulf** [comment]
Hi @wstrinz, hope things are well. Could you try running `diesel database setup` to see if the schema file gets populated?

**Comment by wstrinz** [comment]
Thanks for taking a look! Running that, I get
```
The --database-url argument must be passed, or the DATABASE_URL environment variable must be set.
```

**Comment by wstrinz** [comment]
Copying .env.example over and running `diesel database setup` now gets dsync working:

```
$ cp .env.example .env
$ diesel database setup
$ .cargo/.build/debug/dsync
Running dsync (generating model code from `backend/schema.rs`)
```

But running `create-rust-app` still errors at the same spot

**Comment by wstrinz** [comment]
Seems like everything is working fine if I follow the above steps and then run `cargo tsync`. Feel free to close the issue if you don't want to troubleshoot further!

**Comment by Wulf** [comment]
@wstrinz I'm glad everything's working on your end. It's weird that tsync wasn't run automatically when running `cargo fullstack`.

I'll close this for now, but feel free to report anything else :)
