### ISSUE TITLE
[BUG] Hard-coded URL's should be set by environment variable(s)

### ISSUE THREAD

**Issue by AnthonyMichaelTDM** [Wulf/create-rust-app#75]
https://github.com/Wulf/create-rust-app/blob/5008413e29aeeaf3efb7df80f18cce0b5e6e6d55/create-rust-app/src/auth/controller.rs#L556-L564

As said in the subject, the hard-coded base URL ("http://localhost:3000/") should be set by an environment variable (maybe `PUBLIC_BASE_URL` or something like that) because in a production environment the recipient of the email, an end-user, will not be running the web server on their local machine, the server will (probably) be hosted on a cloud service provider like Amazon AWS, Linode, etc. and that the user connects to through a browser.

I haven't checked the whole codebase yet, but almost all references to https://localhost:3000 should instead read from an environment variable.

Also, the second link in the code snippet above would be https://localhost:3000, not https://localhost:300

**Comment by Wulf** [comment]
Thanks for pointing this out @AnthonyMichaelTDM -- I've been considering various solutions to this but haven't landed on one yet. I was hoping to finish the email builder (#37) first in order to have the best DX. Regardless, I guess we'll need to address this sooner rather than later.

There are two issues here that need to be addressed:
* hardcoded URLs
* hardcoded mail templates

**Comment by AnthonyMichaelTDM** [comment]
I think the most pressing of those issues is the hardcoded urls,

for the hardcoded mail templates we could have a trait, like EmailTemplate, that can be passed as an optional variable to the functions that send the emails, allowing users to define their own templates.

I can work on this in the coming days.

**Comment by Wulf** [comment]
If by functions you mean the auth controller, that’s exactly what I was thinking — it’s the perfect stopgap until we have a complete solution

**Comment by AnthonyMichaelTDM** [comment]
what do you think I should name the environment variable?

**Comment by AnthonyMichaelTDM** [comment]
Actually, now that I think about it, if I do the email template trait thing we don't really need an environment variable for the link urls because the user can just change the url in their template

**Comment by AnthonyMichaelTDM** [comment]
done, check it out in #211 @Wulf and let me know what you think
