### ISSUE TITLE
Print message when server is up (ex: "Listening on http://localhost:3000")

### ISSUE THREAD

**Issue by fosslover69** [Wulf/create-rust-app#83]
I did `create-rust-app` and  then went into the directory and did `cargo run`.

At first I got some errors regarding postgres like:
`[: FATAL: password authentication failed for user "postgres"](https://stackoverflow.com/questions/74481804/psql-error-connection-to-server-at-localhost-1-port-5432-failed-fatal)` 

I went into `/var/lib/pgsql/data/pg_hba.conf` and changed all values with 'ident' to 'trust' (I don't know if its a good practice but went with it just to make the app work) and its fixed

but now when I do `cargo run`

I'm stuck here 

![image](https://user-images.githubusercontent.com/67329471/207042591-caef54bc-a1c1-4523-8c41-d3c8f0b1d0c5.png)

What should I do?

**Comment by AnthonyMichaelTDM** [comment]
To fix the issue with authorizing Postgres, you should've changed the appropriate environment variables in the `.env` file to reflect the username and password for the user you created when installing Postgres.

Regardless, looks like the error in the screenshot has to do with the storage plugin, did you add the environment variables needed to connect to your s3 instance?

**Comment by AnthonyMichaelTDM** [comment]
Also, looks like the program is compiling and running successfully, run `cargo fullstack` to run the backend and sample front end, then view it by going to http://localhost

**Comment by Wulf** [comment]
@fosslover69 thanks for reporting this and for reaching out on discord. I think our conclusion was to introduce a message so that the end-user knows the URL at which the server is being run to make it clear it's running. Right now, it may give the appearance that it's hanging. Definitely a great UX improvement we should add!

**Comment by Wulf** [comment]
Sometime ago, we changed the behaviour of `cargo fullstack` which now prints various URLs:

![image](https://github.com/Wulf/create-rust-app/assets/4259838/1491acd4-36c4-4b3f-bca7-37ebcc247b92)

You can still go back to old behavour by running `cargo backend` and `cargo frontend` as two separate commands
