### ISSUE TITLE
command not found for `create-rust-app` after installing

### ISSUE THREAD

**Issue by ninetynin** [Wulf/create-rust-app#85]
![image](https://user-images.githubusercontent.com/91336664/210197998-9e87ed0b-e759-4178-9c05-c4c06335f580.png)

**Comment by Wulf** [comment]
hey @ninetynin, hope things are well :)

The command is `create-rust-app` without the -cli ending.

**Comment by Wulf** [comment]
@ninetynin can you confirm that your path has the `~/.cargo/bin` path? See these docs: 
https://doc.rust-lang.org/book/ch14-04-installing-binaries.html

**Comment by Wulf** [comment]
Also, really cool to see i3! What distro are you using?

**Comment by Wulf** [comment]
Ah Manjaro, neat :)

Also, that’s super strange — does the file `/home/anand/.cargo/bin/create-rust-app` exist?
